### ISSUE TITLE
GH Actions windows issue

### ISSUE THREAD

**Issue by steckes** [JanWilczek/juce-webview-tutorial#2]
I tried to integrate a juce webview into github actions as well but could find no solution how to make the installation of webview work in the CI pipeline.
I see that here it is a similar issue, do you have any idea how to fix this?

And thank you for making the tutorial :)

**Comment by mikelange49** [comment]
Same for me

**Comment by mikelange49** [comment]
Here's a repo that seems to pass CI using webviews
I didn't look further
https://github.com/greynewell/musegpt

**Comment by steckes** [comment]
Good find, I will take a look at that soon if I can reproduce that and let you know what is the trick :D

**Comment by mikelange49** [comment]
This script my problem
https://github.com/mikelange49/pamplejuce_webview2/commit/51e75dae6d4f157a65010cb8c9024e8cfb7fb15b
(I'm using the pamplejuce template)

**Comment by JanWilczek** [comment]
Hi @steckes , I've fixed WebView2 install script, as you can see, the CI now passes; let me know if it doesn't work for you for some reason. Cheers! :)

**Comment by steckes** [comment]
Wow so cool! Thank you, didn't had time to look back into it, but I will try to update our demo plugin next week.
